version: '3.7'

services:
  mysql:
    container_name: wptunnel_mysql_{SUBDOMAIN}
    image: mysql:5.7
    volumes:
      - /var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  wordpress:
    container_name: wptunnel_wordpress_{SUBDOMAIN}
    depends_on:
      - mysql
    build: ../../docker/wordpress
    expose:
      - "80"
    restart: always
    volumes:
      - {DATA_DIR}/wp-content:/var/www/html/wp-content:rw
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WP_URL: http://{SUBDOMAIN}.wptunnel.com
    healthcheck:
      test: |
          curl --silent --fail http://wordpress:80/wp-admin/install.php ||
          curl --silent --fail http://wordpress:80/index.php ||
          exit 1
      interval: 10s
      timeout: 2s
      retries: 3
  setup:
    container_name: wptunnel_setup_{SUBDOMAIN}
    depends_on:
      - wordpress
    build: ../../docker/wordpress-finalize
  # phpmyadmin:
  #   depends_on:
  #     - db
  #   image: phpmyadmin/phpmyadmin
  #   restart: always
  #   ports:
  #     - 81:80
  #   environment:
  #     PMA_HOST: db
  #     MYSQL_ROOT_PASSWORD: wordpress
  proxy:
    container_name: wptunnel_proxy_{SUBDOMAIN}
    depends_on:
      - wordpress
    build: ./frp-docker